ticket.ticket_type.*:
  type: config_entity
  label: 'Ticket type config'
  mapping:
    ticket_id:
      type: string
      label: 'Ticket ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    uid:
      type: string
    langcode:
      type: string
    ticket_type:
      type: string
      label: 'Ticket Type'
    status:
      type: string
      label: 'Registration Status'
